packages:
  - "packages/*"
  - "apps/*"

autoInstallPeers: true
linkWorkspacePackages: true

allowBuilds:
  "@tailwindcss/oxide": true
  "@vercel/speed-insights": true
  esbuild: false
  msw: false
  protobufjs: false
  sharp: false
  unrs-resolver: false
